/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{ type: "autogenerated", dirName: "." }], */

  docs: [
    {
      type: "category",
      label: "Comenzando con Serpa",
      link: {
        id: "getting-started",
        type: "doc",
      },
      collapsed: true,
      items: ["organizations", "cloud-accounts"],
    },
    {
      type: "category",
      label: "Automatización",
      link: {
        id: "automation/index",
        type: "doc",
      },
      collapsed: true,
      items: ["apps/index"],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
